name: smart_supermarket
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dartx: ^1.2.0
  fluttertoast: ^8.2.12
  pure_dart_ui: ^0.1.10
  icons_plus: ^4.0.0 # 👈 Downgraded for compatibility
  badges: ^2.0.3 # 👈 Downgraded for compatibility
  device_preview: ^1.2.0
  http: ^1.3.0
  qr_code_scanner_plus: ^2.0.10+1
  shared_preferences: ^2.5.3
  flutter_stripe:
  qr_flutter_new: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/Beverages.png
    - assets/images/meat_fish.png
    - assets/images/pick.jpg

  shaders: []

  fonts: []

  generate: false



flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"
    adaptive_icon_background: "#5d8941"
    adaptive_icon_foreground: "assets/images/logo_foreground.png"
